### Site metadata ###

title: Jekyll Blog Demo
description: "Base for a static website blog - built with Jekyll and the default theme"

email:
twitter_username:
github_username: MichaelCurrin
rss: RSS

### Build settings ###

url: https://michaelcurrin.github.io
baseurl: /jekyll-blog-demo

permalink: pretty

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  tools:
    output: true
  languages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - docs/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md
  - sample*.png

liquid:
  error_mode: strict

strict_front_matter: true
